# Generated by Django 4.2.11 on 2024-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocaltionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, verbose_name='设备id')),
                ('location', models.CharField(max_length=64, verbose_name='地址')),
            ],
        ),
    ]
