# Generated by Django 4.2.11 on 2024-03-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsRawMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccc', models.CharField(blank=True, max_length=64, null=True, verbose_name='CCC')),
                ('mac', models.DateTimeField(blank=True, null=True, verbose_name='设备号唯一编码')),
                ('ccid', models.CharField(blank=True, max_length=64, null=True, verbose_name='CCID')),
                ('imei', models.CharField(blank=True, max_length=64, null=True, verbose_name='imei')),
                ('imsi', models.CharField(blank=True, max_length=64, null=True, verbose_name='imsi')),
                ('cstatus', models.CharField(blank=True, max_length=64, null=True, verbose_name='cstatus')),
                ('dsignal', models.CharField(blank=True, max_length=64, null=True, verbose_name='dsignal')),
                ('smokeid', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备ID')),
                ('batterys', models.CharField(blank=True, max_length=64, null=True, verbose_name='batterys')),
                ('createtime', models.CharField(blank=True, max_length=64, null=True, verbose_name='精确到毫秒')),
                ('devicetype', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备类型')),
                ('messagetype', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件类型')),
                ('businesstype', models.CharField(blank=True, max_length=64, null=True, verbose_name='businesstype')),
                ('tamperstatus', models.CharField(blank=True, max_length=64, null=True, verbose_name='tamperstatus')),
                ('voltagevalue', models.CharField(blank=True, max_length=64, null=True, verbose_name='通道名称')),
                ('xdsmokelogid', models.CharField(blank=True, max_length=64, null=True, verbose_name='消息ID')),
                ('statedesc', models.CharField(blank=True, max_length=64, null=True, verbose_name='告警内容')),
                ('tvalue', models.CharField(blank=True, max_length=64, null=True, verbose_name='监测温度，单位°C')),
                ('dataunit', models.CharField(blank=True, max_length=64, null=True, verbose_name='监测单位')),
                ('data', models.CharField(blank=True, max_length=64, null=True, verbose_name='监测值')),
                ('devicename', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备位置')),
            ],
        ),
    ]
