# Generated by Django 4.2.11 on 2024-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='应用名称')),
                ('appid', models.CharField(blank=True, max_length=32, unique=True, verbose_name='appId')),
                ('secret', models.CharField(blank=True, max_length=32, verbose_name='secret')),
                ('expires_in', models.IntegerField(default=86400, verbose_name='有效时间(秒)')),
            ],
        ),
    ]
