# Generated by Django 4.2.11 on 2024-03-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highobjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsRawMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portNo', models.CharField(blank=True, max_length=64, null=True, verbose_name='端口号')),
                ('dateTime', models.DateTimeField(blank=True, null=True, verbose_name='告警时间')),
                ('deviceID', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备ID')),
                ('protocol', models.CharField(blank=True, max_length=64, null=True, verbose_name='protocol')),
                ('channelID', models.CharField(blank=True, max_length=64, null=True, verbose_name='channelID')),
                ('eventType', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件类型')),
                ('ipAddress', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP')),
                ('eventState', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件状态')),
                ('macAddress', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备MAC')),
                ('channelName', models.CharField(blank=True, max_length=64, null=True, verbose_name='通道名称')),
                ('ipv6Address', models.CharField(blank=True, max_length=64, null=True, verbose_name='ipv6')),
                ('protocolType', models.CharField(blank=True, max_length=64, null=True, verbose_name='protocolType')),
                ('activePostCount', models.CharField(blank=True, max_length=64, null=True, verbose_name='activePostCount')),
                ('eventDescription', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件描述')),
                ('isDataRetransmission', models.CharField(blank=True, max_length=64, null=True, verbose_name='isDataRetransmission')),
            ],
        ),
        migrations.DeleteModel(
            name='ApiApplications',
        ),
    ]
